/*
 * Copyright (C) 2026 Jean-Michel Nicolas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// The module that drives the app on a device: it measures cold start and the
// timeline scroll, and it writes the baseline profile the app ships.
//
// Both live here rather than in two modules because they are the same journey
// seen twice — the profile is a recording of what the measurement replays — and
// because a second Gradle module would be a second thing the guard, the gate
// and CI have to name. Ticket 24 is a decision about whether this module earns
// its place; it should not cost more than it has to while it is being judged.
//
// **Nothing here runs in the gate.** Turning the generator off during the build
// is app/build.gradle.kts's job, and it does it: the profile is generated by
// hand, committed as text, and :app:assembleRelease reads that text file. The
// only task of this module the gate names is checkNoGoogleDependencies, which
// resolves a dependency graph and touches no device.

plugins {
    id("com.android.test")
    kotlin("android")
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "app.lenews.baselineprofile"

    // compileSdk, minSdk, targetSdk and buildToolsVersion come from the root
    // build.gradle.kts, which configures this module exactly as it configures
    // the other three.

    defaultConfig {
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // What is being measured and recorded.
    targetProjectPath = ":app"
}

// The application id of the APK under measurement, handed to the tests as an
// instrumentation argument. The build types the baseline profile plugin adds
// are derived from `release` and named by the plugin, so what the app is
// actually called on the device is AGP's answer to give, not a constant to
// write down here and get wrong the day the plugin renames one.
androidComponents {
    onVariants { variant ->
        val builtArtifacts = variant.artifacts.getBuiltArtifactsLoader()
        variant.instrumentationRunnerArguments.put(
            "targetAppId",
            variant.testedApks.map { apks ->
                builtArtifacts.load(apks)?.applicationId
                    ?: throw GradleException("no tested APK to read an application id from")
            }
        )
    }
}

baselineProfile {
    // The device is whatever adb is pinned to, which for this repo is
    // emulator-5554 running bench-pixel6-aosp. A Gradle managed device would
    // download a system image of its own choosing, and the ones it defaults to
    // carry Play Services — see the Google guard in the root build file for why
    // that is not a device this project benchmarks on.
    useConnectedDevices = true
}

dependencies {
    implementation(libs.ext.junit)
    implementation(libs.ext.runner)
    implementation(libs.uiautomator)
    implementation(libs.benchmark.macro.junit4)
}
